Make build fail

diff --git a/.github/workflows/hello.yml b/.github/workflows/hello.yml
--- a/.github/workflows/hello.yml
+++ b/.github/workflows/hello.yml
@@ -17,8 +17,8 @@ jobs:
       - name: get-npm-version
         id: package-version
         uses: martinbeentjes/npm-get-version-action@v1.3.1
-      #- name: Fail
-      #  run: exit 1
+      - name: Fail
+        run: exit 1
   deploy_pre:
     runs-on: ubuntu-latest
     needs: [build]
@@ -31,13 +31,13 @@ jobs:
     runs-on: ubuntu-latest
     needs: [build]
     steps:
-      #- name: Success
-      #  run: exit 0
-      - name: Fail
-        run: exit 1
+      - name: Success
+        run: exit 0
+      #- name: Fail
+      #  run: exit 1
   notify:
     env:
-      VERSION: ${{ needs.build_and_deploy.outputs.app-version }}
+      VERSION: ${{ needs.build.outputs.app-version }}
     if: ${{ always() }}
     needs: [build, deploy_pre, deploy_pro]
     runs-on: ubuntu-latest
