Update hello.yml

diff --git a/.github/workflows/hello.yml b/.github/workflows/hello.yml
--- a/.github/workflows/hello.yml
+++ b/.github/workflows/hello.yml
@@ -7,7 +7,7 @@ on:
   workflow_dispatch:
 
 jobs:
-  build_and_deploy:
+  build:
     runs-on: ubuntu-latest
     outputs:
       app-version: ${{ steps.package-version.outputs.current-version }}
@@ -19,18 +19,33 @@ jobs:
         uses: martinbeentjes/npm-get-version-action@v1.3.1
       #- name: Fail
       #  run: exit 1
+  deploy_pre:
+    runs-on: ubuntu-latest
+    needs: [build]
+    steps:
+      - name: Success
+        run: exit 0
+      #- name: Fail
+      #  run: exit 1
+  deploy_pro:
+    runs-on: ubuntu-latest
+    needs: [build]
+    steps:
+      - name: Success
+        run: exit 0
+      #- name: Fail
+      #  run: exit 1
   notify:
     env:
-      MASTER_BRANCH: 'refs/heads/main'
       VERSION: ${{ needs.build_and_deploy.outputs.app-version }}
     if: ${{ always() }}
-    needs: [build_and_deploy]
+    needs: [build, deploy_pre, deploy_pro]
     runs-on: ubuntu-latest
     steps:
       - name: Send message when deploy is success
-        if: needs.build_and_deploy.result == 'success' && github.ref == env.MASTER_BRANCH
-        run: echo "Deployed *bipiapp* in *Cloud Run*! - Deployed version $VERSION"
+        if: needs.build.result == 'success' && needs.deploy_pre.result == 'success' && needs.deploy_pro.result == 'success'
+        run: echo "Deployed *app* in *Cloud Run*! - Deployed version $VERSION"
 
       - name: Send message when deploy fails
-        if: needs.build_and_deploy.result == 'failure' && github.ref == env.MASTER_BRANCH
-        run: echo "Ha fallado el despliegue de *bipiapp* en Cloud Run $VERSION"
+        if: needs.build_and_deploy.result == 'failure' || needs.deploy_pre.result == 'failure' || needs.deploy_pro.result == 'failure'
+        run: echo "Ha fallado el despliegue de *app* en Cloud Run $VERSION"
